mqtt = net.createConnection(net.TCP, 0)
mqtt:mqtt("ESP8266-2", 30, "user", "password")
mqtt:on("connection", function(con) print("connected") end)
mqtt:connect(1883, "winter.ceit.uq.edu.au")
gpio.mode(3,gpio.INPUT,gpio.PULLUP)
gpio.trig(3, "down",function (level)
    mqtt:send("/topicOut","Pin0Down",0,0)
    print("Sent MQTT Message to /topicOut")    
end)