file.open("init.lua", "w")file.writeline([[print("WIFI control")]])
file.writeline([[wifi.setmode(wifi.SOFTAP)]])
file.writeline([[print("ESP8266 mode is: " .. wifi.getmode())]])
file.writeline([[cfg={}]])
file.writeline([[cfg.ssid="eduroam"]])
file.writeline([[cfg.pwd="100%4Hisglory"]])
file.writeline([[if ssid and password then]])
file.writeline([[print("ESP8266 SSID is: " .. cfg.ssid .. " and PASSWORD is: " .. cfg.password)]])
file.writeline([[end]])
file.writeline([[wifi.ap.config(cfg)]])
file.writeline([[ap_mac = wifi.ap.getmac()]])
file.writeline([[sv=net.createServer(net.TCP,30)]])
file.writeline([[sv:listen(80,function(c)]])
file.writeline([[c:on("receive", function(c, pl)]])
file.writeline([[print(string.len(pl))]])
file.writeline([[print(string.match(pl,"GET"))]])
file.writeline([[ssid_start,ssid_end=string.find(pl,"SSID=")]])
file.writeline([[if ssid_start and ssid_end then]])
file.writeline([[amper1_start, amper1_end =string.find(pl,"&", ssid_end+1)]])
file.writeline([[if amper1_start and amper1_end then]])
file.writeline([[http_start, http_end =string.find(pl,"HTTP/1.1", ssid_end+1)]])
file.writeline([[if http_start and http_end then]])
file.writeline([[ssid=string.sub(pl,ssid_end+1, amper1_start-1)]])
file.writeline([[password=string.sub(pl,amper1_end+10, http_start-2)]])
file.writeline([[print("ESP8266 connecting to SSID: " .. ssid .. " with PASSWORD: " .. password)]])
file.writeline([[if ssid and password then]])
file.writeline([[sv:close()]])
file.writeline([[wifi.setmode(wifi.STATIONAP)]])
file.writeline([[print("ESP8266 mode now is: " .. wifi.getmode())]])
file.writeline([[wifi.sta.config(ssid,password)]])
file.writeline([[print("Setting up ESP8266 for station mode…Please wait.")]])
file.writeline([[tmr.delay(10000000)]])
file.writeline([[print("ESP8266 STATION IP now is: " .. wifi.sta.getip())]])
file.writeline([[print("ESP8266 AP IP now is: " .. wifi.ap.getip())]])
file.writeline([[gpio.mode(8,gpio.OUTPUT)]])
file.writeline([[gpio.mode(9,gpio.OUTPUT)]])
file.writeline([[tmr.delay(10)]])
file.writeline([[gpio.write(8,gpio.HIGH)]])
file.writeline([[tmr.delay(10)]])
file.writeline([[gpio.write(8,gpio.LOW)]])
file.writeline([[sv=net.createServer(net.TCP, 30)]])
file.writeline([[sv:listen(9999,function(c)]])
file.writeline([[c:on("receive", function(c, pl)]])
file.writeline([[if tonumber(pl) ~= nil then]])
file.writeline([[if tonumber(pl) >= 1 and tonumber(pl) <= 16 then]])
file.writeline([[print(tonumber(pl))]])
file.writeline([[tmr.delay(10)]])
file.writeline([[gpio.write(8,gpio.HIGH)]])
file.writeline([[tmr.delay(10)]])
file.writeline([[gpio.write(8,gpio.LOW)]])
file.writeline([[for count =1,tonumber(pl) do]])
file.writeline([[print(count)]])
file.writeline([[tmr.delay(10)]])
file.writeline([[gpio.write(9,gpio.LOW)]])
file.writeline([[tmr.delay(10)]])
file.writeline([[gpio.write(9,gpio.HIGH)]])
file.writeline([[c:send("Sequence finished")]])
file.writeline([[end]])
file.writeline([[end]])
file.writeline([[end]])
file.writeline([[print("ESP8266 STATION IP now is: " .. new_ip)]])
file.writeline([[c:send("ESP8266 STATION IP now is: " .. new_ip)]])
file.writeline([[c:send("Action completed")]])
file.writeline([[end)]])
file.writeline([[end)]])
file.writeline([[end]])
file.writeline([[end]])
file.writeline([[end]])
file.writeline([[end]])
file.writeline([[c:send("<!DOCTYPE html> ")]])
file.writeline([[c:send("<html lang='en'> ")]])
file.writeline([[c:send("<body> ")]])
file.writeline([[c:send("<h1>ESP8266 Wireless control setup</h1> ")]])
file.writeline([[mac_mess1 = "The module MAC address is: " .. ap_mac]])
file.writeline([[mac_mess2 = "You will need this MAC address to find the IP address of the module, please take note of it."]])
file.writeline([[c:send("<h2>" .. mac_mess1 .. "</h2> ")]])
file.writeline([[c:send("<h2>" .. mac_mess2 .. "</h2> ")]])
file.writeline([[c:send("<h2>Enter SSID and Password for your WIFI router</h2> ")]])
file.writeline([[c:send("</form> </body> </html>")]])
file.writeline([[c:send("<form action=\" method='get'>")]])
file.writeline([[c:send("SSID:")]])
file.writeline([[c:send("<input type='text' name='SSID' value=\" maxlength='100' />")]])
file.writeline([[c:send("<br />")]])
file.writeline([[c:send("Password:")]])
file.writeline([[c:send("<input type='text' name='Password' value=\" maxlength='100' />")]])
file.writeline([[c:send("<input type='submit' value='Submit' />")]])
file.writeline([[end)]])
file.writeline([[end)]])
file.close()